spring:
  profiles:
    group:
      test: "test"
  r2dbc:
    url: r2dbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${DB_NAME}
    password: ${MYSQL_PASSWORD}
    username: ${MYSQL_USERNAME}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false

psp:
  toss:
    secretKey: ${TOSS_SECRET_KEY}
    url: ${TOSS_PAYMENTS_API_URL}